#pragma once
// Do not directly modify.
// Generated by scripts/img2pixel.py assets/segments --invert

#include <stdint.h>

typedef struct {
    uint16_t width;
    uint16_t height;
    const char data[];
} glyph_t;

extern const glyph_t img_clock_0;
extern const glyph_t img_clock_1;
extern const glyph_t img_clock_2;
extern const glyph_t img_clock_3;
extern const glyph_t img_clock_4;
extern const glyph_t img_clock_5;
extern const glyph_t img_clock_6;
extern const glyph_t img_clock_7;
extern const glyph_t img_clock_8;
extern const glyph_t img_clock_9;
extern const glyph_t img_colon;
extern const glyph_t img_erase;
extern const glyph_t img_error;
extern const glyph_t img_flash;
extern const glyph_t img_hash;
extern const glyph_t img_idle;
extern const glyph_t img_mismatch;
extern const glyph_t img_prog;
extern const glyph_t img_progress_0;
extern const glyph_t img_progress_1;
extern const glyph_t img_progress_10;
extern const glyph_t img_progress_2;
extern const glyph_t img_progress_3;
extern const glyph_t img_progress_4;
extern const glyph_t img_progress_5;
extern const glyph_t img_progress_6;
extern const glyph_t img_progress_7;
extern const glyph_t img_progress_8;
extern const glyph_t img_progress_9;
extern const glyph_t img_ram;
extern const glyph_t img_run_0;
extern const glyph_t img_run_1;
extern const glyph_t img_run_2;
extern const glyph_t img_run_3;
extern const glyph_t img_run_4;
extern const glyph_t img_run_5;
extern const glyph_t img_run_6;
extern const glyph_t img_run_7;
extern const glyph_t img_run_8;
extern const glyph_t img_run_9;
extern const glyph_t img_sleep;
extern const glyph_t img_z_0;
extern const glyph_t img_z_1;
extern const glyph_t img_z_2;
