#pragma once
// Do not directly modify.
// Generated by scripts/img2pixel.py assets/segments --invert

#include <stdint.h>

typedef struct {
    uint16_t width;
    uint16_t height;
    const char logo[];
} retro_logo_image;

extern const retro_logo_image img_clock_0;
extern const retro_logo_image img_clock_1;
extern const retro_logo_image img_clock_2;
extern const retro_logo_image img_clock_3;
extern const retro_logo_image img_clock_4;
extern const retro_logo_image img_clock_5;
extern const retro_logo_image img_clock_6;
extern const retro_logo_image img_clock_7;
extern const retro_logo_image img_clock_8;
extern const retro_logo_image img_clock_9;
extern const retro_logo_image img_colon;
extern const retro_logo_image img_erase;
extern const retro_logo_image img_error;
extern const retro_logo_image img_flash;
extern const retro_logo_image img_hash;
extern const retro_logo_image img_idle;
extern const retro_logo_image img_mismatch;
extern const retro_logo_image img_prog;
extern const retro_logo_image img_progress_0;
extern const retro_logo_image img_progress_1;
extern const retro_logo_image img_progress_10;
extern const retro_logo_image img_progress_2;
extern const retro_logo_image img_progress_3;
extern const retro_logo_image img_progress_4;
extern const retro_logo_image img_progress_5;
extern const retro_logo_image img_progress_6;
extern const retro_logo_image img_progress_7;
extern const retro_logo_image img_progress_8;
extern const retro_logo_image img_progress_9;
extern const retro_logo_image img_ram;
extern const retro_logo_image img_run_0;
extern const retro_logo_image img_run_1;
extern const retro_logo_image img_run_2;
extern const retro_logo_image img_run_3;
extern const retro_logo_image img_run_4;
extern const retro_logo_image img_run_5;
extern const retro_logo_image img_run_6;
extern const retro_logo_image img_run_7;
extern const retro_logo_image img_run_8;
extern const retro_logo_image img_run_9;
extern const retro_logo_image img_sleep;
extern const retro_logo_image img_sleep_mouth;
extern const retro_logo_image img_z_0;
extern const retro_logo_image img_z_1;
extern const retro_logo_image img_z_2;
